name: re
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_dotenv: ^5.2.1 # Or the latest version
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  camera: ^0.11.1
  confetti: ^0.8.0
  opencv_4: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Re.mp4
    - assets/.env
    - assets/1.png
    - assets/2.png
    - assets/3.png
